connected to http://jerrylsu.net
comment created: {"id": 2, "parent": null, "created": 1617013222.279301, "modified": null, "mode": 2, "text": "<p>sdsdsdsds</p>", "author": "jerry", "website": "http://jerrylsu.net", "likes": 0, "dislikes": 0, "notification": 0, "hash": "7cc96e8576d8"}
connected to http://jerrylsu.net
comment 1 deleted
comment 2 deleted
connected to SMTP server
connected to http://jerrylsu.net
connected to SMTP server
connected to http://jerrylsu.net
connected to SMTP server
connected to http://jerrylsu.net
GET /id/1/activate/MQ.YGGq8Q.6OWkhZzHmpe8UH4z8VMzjjSX5Gw
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 635, in moderate
    thread = self.threads.get(item['tid'])
TypeError: 'NoneType' object is not subscriptable
connected to SMTP server
connected to http://jerrylsu.net
POST /count
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 964, in counts
    return JSON(self.comments.count(*data), 200)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 332, in count
    threads = dict(self.db.execute([
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
POST /count
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 964, in counts
    return JSON(self.comments.count(*data), 200)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 332, in count
    threads = dict(self.db.execute([
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
POST /count
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 964, in counts
    return JSON(self.comments.count(*data), 200)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 332, in count
    threads = dict(self.db.execute([
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
POST /count
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 964, in counts
    return JSON(self.comments.count(*data), 200)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 332, in count
    threads = dict(self.db.execute([
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
POST /count
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 964, in counts
    return JSON(self.comments.count(*data), 200)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 332, in count
    threads = dict(self.db.execute([
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
POST /count
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 964, in counts
    return JSON(self.comments.count(*data), 200)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 332, in count
    threads = dict(self.db.execute([
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
POST /count
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 964, in counts
    return JSON(self.comments.count(*data), 200)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 332, in count
    threads = dict(self.db.execute([
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
GET /
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 791, in fetch
    reply_counts = self.comments.reply_count(uri, after=args['after'])
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 325, in reply_count
    return dict(self.db.execute(sql, [url, mode, mode, after]).fetchall())
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
GET /
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 791, in fetch
    reply_counts = self.comments.reply_count(uri, after=args['after'])
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 325, in reply_count
    return dict(self.db.execute(sql, [url, mode, mode, after]).fetchall())
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
POST /count
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 964, in counts
    return JSON(self.comments.count(*data), 200)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 332, in count
    threads = dict(self.db.execute([
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
GET /
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 791, in fetch
    reply_counts = self.comments.reply_count(uri, after=args['after'])
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 325, in reply_count
    return dict(self.db.execute(sql, [url, mode, mode, after]).fetchall())
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
POST /count
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 964, in counts
    return JSON(self.comments.count(*data), 200)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 332, in count
    threads = dict(self.db.execute([
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
POST /count
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 964, in counts
    return JSON(self.comments.count(*data), 200)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 332, in count
    threads = dict(self.db.execute([
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
POST /count
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 964, in counts
    return JSON(self.comments.count(*data), 200)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 332, in count
    threads = dict(self.db.execute([
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
POST /count
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 964, in counts
    return JSON(self.comments.count(*data), 200)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 332, in count
    threads = dict(self.db.execute([
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
POST /count
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 964, in counts
    return JSON(self.comments.count(*data), 200)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 332, in count
    threads = dict(self.db.execute([
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
POST /count
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 964, in counts
    return JSON(self.comments.count(*data), 200)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 332, in count
    threads = dict(self.db.execute([
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
GET /
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 791, in fetch
    reply_counts = self.comments.reply_count(uri, after=args['after'])
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 325, in reply_count
    return dict(self.db.execute(sql, [url, mode, mode, after]).fetchall())
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
POST /count
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 964, in counts
    return JSON(self.comments.count(*data), 200)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 332, in count
    threads = dict(self.db.execute([
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
POST /count
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 964, in counts
    return JSON(self.comments.count(*data), 200)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 332, in count
    threads = dict(self.db.execute([
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
GET /
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 791, in fetch
    reply_counts = self.comments.reply_count(uri, after=args['after'])
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 325, in reply_count
    return dict(self.db.execute(sql, [url, mode, mode, after]).fetchall())
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
POST /count
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 964, in counts
    return JSON(self.comments.count(*data), 200)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 332, in count
    threads = dict(self.db.execute([
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
GET /
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 791, in fetch
    reply_counts = self.comments.reply_count(uri, after=args['after'])
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 325, in reply_count
    return dict(self.db.execute(sql, [url, mode, mode, after]).fetchall())
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
GET /
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 791, in fetch
    reply_counts = self.comments.reply_count(uri, after=args['after'])
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 325, in reply_count
    return dict(self.db.execute(sql, [url, mode, mode, after]).fetchall())
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
POST /count
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 964, in counts
    return JSON(self.comments.count(*data), 200)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 332, in count
    threads = dict(self.db.execute([
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
POST /count
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 964, in counts
    return JSON(self.comments.count(*data), 200)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 332, in count
    threads = dict(self.db.execute([
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
POST /count
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 964, in counts
    return JSON(self.comments.count(*data), 200)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 332, in count
    threads = dict(self.db.execute([
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
POST /count
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 964, in counts
    return JSON(self.comments.count(*data), 200)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 332, in count
    threads = dict(self.db.execute([
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
POST /count
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 964, in counts
    return JSON(self.comments.count(*data), 200)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 332, in count
    threads = dict(self.db.execute([
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
POST /count
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 964, in counts
    return JSON(self.comments.count(*data), 200)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 332, in count
    threads = dict(self.db.execute([
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
GET /
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 791, in fetch
    reply_counts = self.comments.reply_count(uri, after=args['after'])
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 325, in reply_count
    return dict(self.db.execute(sql, [url, mode, mode, after]).fetchall())
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
POST /count
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 964, in counts
    return JSON(self.comments.count(*data), 200)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 332, in count
    threads = dict(self.db.execute([
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
GET /
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 791, in fetch
    reply_counts = self.comments.reply_count(uri, after=args['after'])
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 325, in reply_count
    return dict(self.db.execute(sql, [url, mode, mode, after]).fetchall())
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
GET /
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 791, in fetch
    reply_counts = self.comments.reply_count(uri, after=args['after'])
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 325, in reply_count
    return dict(self.db.execute(sql, [url, mode, mode, after]).fetchall())
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
POST /count
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 964, in counts
    return JSON(self.comments.count(*data), 200)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 332, in count
    threads = dict(self.db.execute([
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
POST /count
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 964, in counts
    return JSON(self.comments.count(*data), 200)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 332, in count
    threads = dict(self.db.execute([
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
POST /count
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 964, in counts
    return JSON(self.comments.count(*data), 200)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 332, in count
    threads = dict(self.db.execute([
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
GET /
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 791, in fetch
    reply_counts = self.comments.reply_count(uri, after=args['after'])
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 325, in reply_count
    return dict(self.db.execute(sql, [url, mode, mode, after]).fetchall())
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
POST /count
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 964, in counts
    return JSON(self.comments.count(*data), 200)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 332, in count
    threads = dict(self.db.execute([
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
GET /
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 791, in fetch
    reply_counts = self.comments.reply_count(uri, after=args['after'])
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 325, in reply_count
    return dict(self.db.execute(sql, [url, mode, mode, after]).fetchall())
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
POST /count
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 964, in counts
    return JSON(self.comments.count(*data), 200)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 332, in count
    threads = dict(self.db.execute([
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
POST /count
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 964, in counts
    return JSON(self.comments.count(*data), 200)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 332, in count
    threads = dict(self.db.execute([
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
GET /
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 791, in fetch
    reply_counts = self.comments.reply_count(uri, after=args['after'])
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 325, in reply_count
    return dict(self.db.execute(sql, [url, mode, mode, after]).fetchall())
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
POST /count
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 964, in counts
    return JSON(self.comments.count(*data), 200)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 332, in count
    threads = dict(self.db.execute([
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
POST /count
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 964, in counts
    return JSON(self.comments.count(*data), 200)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 332, in count
    threads = dict(self.db.execute([
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
POST /count
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 964, in counts
    return JSON(self.comments.count(*data), 200)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 332, in count
    threads = dict(self.db.execute([
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
POST /count
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 964, in counts
    return JSON(self.comments.count(*data), 200)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 332, in count
    threads = dict(self.db.execute([
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
POST /count
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 964, in counts
    return JSON(self.comments.count(*data), 200)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 332, in count
    threads = dict(self.db.execute([
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
POST /count
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 964, in counts
    return JSON(self.comments.count(*data), 200)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 332, in count
    threads = dict(self.db.execute([
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
POST /count
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 964, in counts
    return JSON(self.comments.count(*data), 200)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 332, in count
    threads = dict(self.db.execute([
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
POST /count
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 964, in counts
    return JSON(self.comments.count(*data), 200)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 332, in count
    threads = dict(self.db.execute([
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
GET /
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 791, in fetch
    reply_counts = self.comments.reply_count(uri, after=args['after'])
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 325, in reply_count
    return dict(self.db.execute(sql, [url, mode, mode, after]).fetchall())
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
POST /count
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 964, in counts
    return JSON(self.comments.count(*data), 200)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 332, in count
    threads = dict(self.db.execute([
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
POST /count
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 964, in counts
    return JSON(self.comments.count(*data), 200)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 332, in count
    threads = dict(self.db.execute([
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
POST /count
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 964, in counts
    return JSON(self.comments.count(*data), 200)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 332, in count
    threads = dict(self.db.execute([
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
POST /count
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 964, in counts
    return JSON(self.comments.count(*data), 200)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 332, in count
    threads = dict(self.db.execute([
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
POST /count
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 964, in counts
    return JSON(self.comments.count(*data), 200)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 332, in count
    threads = dict(self.db.execute([
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
GET /
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 791, in fetch
    reply_counts = self.comments.reply_count(uri, after=args['after'])
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 325, in reply_count
    return dict(self.db.execute(sql, [url, mode, mode, after]).fetchall())
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
POST /count
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 964, in counts
    return JSON(self.comments.count(*data), 200)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 332, in count
    threads = dict(self.db.execute([
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
POST /count
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 964, in counts
    return JSON(self.comments.count(*data), 200)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 332, in count
    threads = dict(self.db.execute([
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
GET /
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 791, in fetch
    reply_counts = self.comments.reply_count(uri, after=args['after'])
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 325, in reply_count
    return dict(self.db.execute(sql, [url, mode, mode, after]).fetchall())
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
POST /new
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 88, in dec
    return func(self, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 278, in new
    if uri not in self.threads:
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/threads.py", line 22, in __contains__
    return self.db.execute("SELECT title FROM threads WHERE uri=?", (uri, )) \
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: threads
POST /new
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 88, in dec
    return func(self, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 278, in new
    if uri not in self.threads:
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/threads.py", line 22, in __contains__
    return self.db.execute("SELECT title FROM threads WHERE uri=?", (uri, )) \
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: threads
POST /new
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 88, in dec
    return func(self, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 278, in new
    if uri not in self.threads:
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/threads.py", line 22, in __contains__
    return self.db.execute("SELECT title FROM threads WHERE uri=?", (uri, )) \
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: threads
POST /new
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 88, in dec
    return func(self, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 278, in new
    if uri not in self.threads:
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/threads.py", line 22, in __contains__
    return self.db.execute("SELECT title FROM threads WHERE uri=?", (uri, )) \
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: threads
POST /new
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 88, in dec
    return func(self, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 278, in new
    if uri not in self.threads:
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/threads.py", line 22, in __contains__
    return self.db.execute("SELECT title FROM threads WHERE uri=?", (uri, )) \
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: threads
POST /new
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 88, in dec
    return func(self, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 278, in new
    if uri not in self.threads:
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/threads.py", line 22, in __contains__
    return self.db.execute("SELECT title FROM threads WHERE uri=?", (uri, )) \
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: threads
POST /new
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 88, in dec
    return func(self, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 278, in new
    if uri not in self.threads:
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/threads.py", line 22, in __contains__
    return self.db.execute("SELECT title FROM threads WHERE uri=?", (uri, )) \
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: threads
POST /new
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 88, in dec
    return func(self, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 278, in new
    if uri not in self.threads:
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/threads.py", line 22, in __contains__
    return self.db.execute("SELECT title FROM threads WHERE uri=?", (uri, )) \
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: threads
POST /new
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 88, in dec
    return func(self, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 278, in new
    if uri not in self.threads:
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/threads.py", line 22, in __contains__
    return self.db.execute("SELECT title FROM threads WHERE uri=?", (uri, )) \
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: threads
POST /new
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 88, in dec
    return func(self, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 278, in new
    if uri not in self.threads:
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/threads.py", line 22, in __contains__
    return self.db.execute("SELECT title FROM threads WHERE uri=?", (uri, )) \
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: threads
POST /new
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 88, in dec
    return func(self, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 278, in new
    if uri not in self.threads:
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/threads.py", line 22, in __contains__
    return self.db.execute("SELECT title FROM threads WHERE uri=?", (uri, )) \
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: threads
POST /new
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 88, in dec
    return func(self, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 278, in new
    if uri not in self.threads:
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/threads.py", line 22, in __contains__
    return self.db.execute("SELECT title FROM threads WHERE uri=?", (uri, )) \
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: threads
POST /new
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 88, in dec
    return func(self, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 278, in new
    if uri not in self.threads:
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/threads.py", line 22, in __contains__
    return self.db.execute("SELECT title FROM threads WHERE uri=?", (uri, )) \
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: threads
POST /new
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 88, in dec
    return func(self, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 278, in new
    if uri not in self.threads:
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/threads.py", line 22, in __contains__
    return self.db.execute("SELECT title FROM threads WHERE uri=?", (uri, )) \
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: threads
POST /new
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 88, in dec
    return func(self, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 278, in new
    if uri not in self.threads:
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/threads.py", line 22, in __contains__
    return self.db.execute("SELECT title FROM threads WHERE uri=?", (uri, )) \
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: threads
POST /new
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 88, in dec
    return func(self, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 278, in new
    if uri not in self.threads:
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/threads.py", line 22, in __contains__
    return self.db.execute("SELECT title FROM threads WHERE uri=?", (uri, )) \
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: threads
POST /new
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 88, in dec
    return func(self, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 278, in new
    if uri not in self.threads:
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/threads.py", line 22, in __contains__
    return self.db.execute("SELECT title FROM threads WHERE uri=?", (uri, )) \
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: threads
POST /new
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 88, in dec
    return func(self, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 278, in new
    if uri not in self.threads:
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/threads.py", line 22, in __contains__
    return self.db.execute("SELECT title FROM threads WHERE uri=?", (uri, )) \
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: threads
POST /new
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 88, in dec
    return func(self, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 278, in new
    if uri not in self.threads:
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/threads.py", line 22, in __contains__
    return self.db.execute("SELECT title FROM threads WHERE uri=?", (uri, )) \
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: threads
POST /new
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 88, in dec
    return func(self, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 278, in new
    if uri not in self.threads:
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/threads.py", line 22, in __contains__
    return self.db.execute("SELECT title FROM threads WHERE uri=?", (uri, )) \
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: threads
POST /new
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 88, in dec
    return func(self, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 278, in new
    if uri not in self.threads:
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/threads.py", line 22, in __contains__
    return self.db.execute("SELECT title FROM threads WHERE uri=?", (uri, )) \
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: threads
POST /new
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 88, in dec
    return func(self, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 278, in new
    if uri not in self.threads:
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/threads.py", line 22, in __contains__
    return self.db.execute("SELECT title FROM threads WHERE uri=?", (uri, )) \
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: threads
POST /new
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 88, in dec
    return func(self, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 278, in new
    if uri not in self.threads:
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/threads.py", line 22, in __contains__
    return self.db.execute("SELECT title FROM threads WHERE uri=?", (uri, )) \
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: threads
POST /new
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 88, in dec
    return func(self, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 278, in new
    if uri not in self.threads:
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/threads.py", line 22, in __contains__
    return self.db.execute("SELECT title FROM threads WHERE uri=?", (uri, )) \
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: threads
POST /new
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 88, in dec
    return func(self, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 278, in new
    if uri not in self.threads:
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/threads.py", line 22, in __contains__
    return self.db.execute("SELECT title FROM threads WHERE uri=?", (uri, )) \
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: threads
POST /new
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 88, in dec
    return func(self, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 278, in new
    if uri not in self.threads:
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/threads.py", line 22, in __contains__
    return self.db.execute("SELECT title FROM threads WHERE uri=?", (uri, )) \
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: threads
POST /new
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 88, in dec
    return func(self, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 278, in new
    if uri not in self.threads:
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/threads.py", line 22, in __contains__
    return self.db.execute("SELECT title FROM threads WHERE uri=?", (uri, )) \
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: threads
POST /count
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 964, in counts
    return JSON(self.comments.count(*data), 200)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 332, in count
    threads = dict(self.db.execute([
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
POST /count
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 964, in counts
    return JSON(self.comments.count(*data), 200)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 332, in count
    threads = dict(self.db.execute([
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
GET /
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 791, in fetch
    reply_counts = self.comments.reply_count(uri, after=args['after'])
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 325, in reply_count
    return dict(self.db.execute(sql, [url, mode, mode, after]).fetchall())
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
POST /new
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 88, in dec
    return func(self, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 278, in new
    if uri not in self.threads:
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/threads.py", line 22, in __contains__
    return self.db.execute("SELECT title FROM threads WHERE uri=?", (uri, )) \
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: threads
POST /count
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 964, in counts
    return JSON(self.comments.count(*data), 200)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 332, in count
    threads = dict(self.db.execute([
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
POST /count
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 964, in counts
    return JSON(self.comments.count(*data), 200)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 332, in count
    threads = dict(self.db.execute([
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
GET /
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 791, in fetch
    reply_counts = self.comments.reply_count(uri, after=args['after'])
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 325, in reply_count
    return dict(self.db.execute(sql, [url, mode, mode, after]).fetchall())
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
GET /admin
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 1141, in admin
    for comment in list(comments):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 196, in fetchall
    rv = self.db.execute(sql, sql_args).fetchall()
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
connected to SMTP server
connected to http://jerrylsu.net
POST /count
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 964, in counts
    return JSON(self.comments.count(*data), 200)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 332, in count
    threads = dict(self.db.execute([
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
POST /count
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 964, in counts
    return JSON(self.comments.count(*data), 200)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 332, in count
    threads = dict(self.db.execute([
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
POST /count
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 964, in counts
    return JSON(self.comments.count(*data), 200)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 332, in count
    threads = dict(self.db.execute([
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
POST /count
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 964, in counts
    return JSON(self.comments.count(*data), 200)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 332, in count
    threads = dict(self.db.execute([
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
GET /
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 791, in fetch
    reply_counts = self.comments.reply_count(uri, after=args['after'])
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 325, in reply_count
    return dict(self.db.execute(sql, [url, mode, mode, after]).fetchall())
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
POST /new
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 88, in dec
    return func(self, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 278, in new
    if uri not in self.threads:
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/threads.py", line 22, in __contains__
    return self.db.execute("SELECT title FROM threads WHERE uri=?", (uri, )) \
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: threads
POST /count
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 964, in counts
    return JSON(self.comments.count(*data), 200)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 332, in count
    threads = dict(self.db.execute([
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
GET /
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 791, in fetch
    reply_counts = self.comments.reply_count(uri, after=args['after'])
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 325, in reply_count
    return dict(self.db.execute(sql, [url, mode, mode, after]).fetchall())
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
POST /new
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 88, in dec
    return func(self, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 278, in new
    if uri not in self.threads:
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/threads.py", line 22, in __contains__
    return self.db.execute("SELECT title FROM threads WHERE uri=?", (uri, )) \
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: threads
POST /new
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 88, in dec
    return func(self, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 278, in new
    if uri not in self.threads:
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/threads.py", line 22, in __contains__
    return self.db.execute("SELECT title FROM threads WHERE uri=?", (uri, )) \
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: threads
POST /new
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 88, in dec
    return func(self, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 278, in new
    if uri not in self.threads:
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/threads.py", line 22, in __contains__
    return self.db.execute("SELECT title FROM threads WHERE uri=?", (uri, )) \
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: threads
POST /new
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 88, in dec
    return func(self, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 278, in new
    if uri not in self.threads:
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/threads.py", line 22, in __contains__
    return self.db.execute("SELECT title FROM threads WHERE uri=?", (uri, )) \
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: threads
POST /new
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 88, in dec
    return func(self, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 278, in new
    if uri not in self.threads:
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/threads.py", line 22, in __contains__
    return self.db.execute("SELECT title FROM threads WHERE uri=?", (uri, )) \
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: threads
POST /new
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 88, in dec
    return func(self, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 278, in new
    if uri not in self.threads:
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/threads.py", line 22, in __contains__
    return self.db.execute("SELECT title FROM threads WHERE uri=?", (uri, )) \
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: threads
POST /new
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 88, in dec
    return func(self, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 278, in new
    if uri not in self.threads:
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/threads.py", line 22, in __contains__
    return self.db.execute("SELECT title FROM threads WHERE uri=?", (uri, )) \
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: threads
POST /new
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 88, in dec
    return func(self, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 278, in new
    if uri not in self.threads:
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/threads.py", line 22, in __contains__
    return self.db.execute("SELECT title FROM threads WHERE uri=?", (uri, )) \
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: threads
POST /new
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 88, in dec
    return func(self, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 278, in new
    if uri not in self.threads:
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/threads.py", line 22, in __contains__
    return self.db.execute("SELECT title FROM threads WHERE uri=?", (uri, )) \
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: threads
POST /new
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 88, in dec
    return func(self, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 278, in new
    if uri not in self.threads:
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/threads.py", line 22, in __contains__
    return self.db.execute("SELECT title FROM threads WHERE uri=?", (uri, )) \
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: threads
POST /new
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 88, in dec
    return func(self, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 278, in new
    if uri not in self.threads:
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/threads.py", line 22, in __contains__
    return self.db.execute("SELECT title FROM threads WHERE uri=?", (uri, )) \
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: threads
POST /new
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 88, in dec
    return func(self, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 278, in new
    if uri not in self.threads:
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/threads.py", line 22, in __contains__
    return self.db.execute("SELECT title FROM threads WHERE uri=?", (uri, )) \
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: threads
POST /new
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 88, in dec
    return func(self, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 278, in new
    if uri not in self.threads:
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/threads.py", line 22, in __contains__
    return self.db.execute("SELECT title FROM threads WHERE uri=?", (uri, )) \
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: threads
POST /new
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 88, in dec
    return func(self, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 278, in new
    if uri not in self.threads:
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/threads.py", line 22, in __contains__
    return self.db.execute("SELECT title FROM threads WHERE uri=?", (uri, )) \
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: threads
POST /count
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 964, in counts
    return JSON(self.comments.count(*data), 200)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 332, in count
    threads = dict(self.db.execute([
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
GET /
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 791, in fetch
    reply_counts = self.comments.reply_count(uri, after=args['after'])
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/comments.py", line 325, in reply_count
    return dict(self.db.execute(sql, [url, mode, mode, after]).fetchall())
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: comments
POST /new
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 88, in dec
    return func(self, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 278, in new
    if uri not in self.threads:
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/threads.py", line 22, in __contains__
    return self.db.execute("SELECT title FROM threads WHERE uri=?", (uri, )) \
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: threads
POST /new
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 88, in dec
    return func(self, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 278, in new
    if uri not in self.threads:
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/threads.py", line 22, in __contains__
    return self.db.execute("SELECT title FROM threads WHERE uri=?", (uri, )) \
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: threads
POST /new
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 88, in dec
    return func(self, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 278, in new
    if uri not in self.threads:
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/threads.py", line 22, in __contains__
    return self.db.execute("SELECT title FROM threads WHERE uri=?", (uri, )) \
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: threads
POST /new
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 88, in dec
    return func(self, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 278, in new
    if uri not in self.threads:
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/threads.py", line 22, in __contains__
    return self.db.execute("SELECT title FROM threads WHERE uri=?", (uri, )) \
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: threads
POST /new
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 88, in dec
    return func(self, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 278, in new
    if uri not in self.threads:
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/threads.py", line 22, in __contains__
    return self.db.execute("SELECT title FROM threads WHERE uri=?", (uri, )) \
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: threads
POST /new
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 88, in dec
    return func(self, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 278, in new
    if uri not in self.threads:
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/threads.py", line 22, in __contains__
    return self.db.execute("SELECT title FROM threads WHERE uri=?", (uri, )) \
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: threads
POST /new
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 88, in dec
    return func(self, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/__init__.py", line 45, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 278, in new
    if uri not in self.threads:
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/threads.py", line 22, in __contains__
    return self.db.execute("SELECT title FROM threads WHERE uri=?", (uri, )) \
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/db/__init__.py", line 60, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: no such table: threads
connected to SMTP server
connected to http://jerrylsu.net
connected to SMTP server
connected to http://jerrylsu.net
GET /id/1/activate/MQ.YmX9Fg.ebJ_ghgZL2hKMcyhQCYqqfKfYHk
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 635, in moderate
    thread = self.threads.get(item['tid'])
TypeError: 'NoneType' object is not subscriptable
GET /id/1/activate/MQ.YmX9Fg.ebJ_ghgZL2hKMcyhQCYqqfKfYHk
Traceback (most recent call last):
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/__init__.py", line 150, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/conda/envs/blog/lib/python3.8/site-packages/isso/views/comments.py", line 635, in moderate
    thread = self.threads.get(item['tid'])
TypeError: 'NoneType' object is not subscriptable
connected to SMTP server
connected to http://jerrylsu.net
connected to SMTP server
connected to http://jerrylsu.net
connected to SMTP server
connected to http://jerrylsu.net
